[package]
name = "catbox-rs"
version = "0.1.0"
edition = "2024"
readme = "README.md"
#license = "GPL-3"
license-file = "LICENSE"
repository = "https://github.com/CoffeeCatRailway/catbox-rs"
homepage = "https://github.com/CoffeeCatRailway/catbox-rs"

[dependencies]
glow = "0.16.0"
glam = "0.30.9"
bytemuck = "1.24.0"

glutin = "0.32.3"
glutin-winit = "0.5.0"
winit = { version = "0.30.12", features = ["rwh_06"] }
winit_input_helper = "0.17.0"
raw-window-handle = "0.6.2"

env_logger = "0.11.8"
log = "0.4.29"
log-panics = { version = "2.1.0", features = ["with-backtrace"] }
