[package]
name = "catbox-rs"
version = "0.6.1"
edition = "2024"
readme = "README.md"
#license = "GPL-3"
license-file = "LICENSE"
repository = "https://github.com/CoffeeCatRailway/catbox-rs"
homepage = "https://github.com/CoffeeCatRailway/catbox-rs"
publish = false

[dependencies]
glow = { version = "0.16.0", features = ["log"] }
glam = "0.30.9"
bytemuck = "1.24.0"

glutin = "0.32.3"
glutin-winit = "0.5.0"
winit = { version = "0.30.12", features = ["rwh_06"] }
winit_input_helper = "0.17.0"
raw-window-handle = "0.6.2"

dear-imgui-rs = { version = "0.8.0", features = ["glam"] }
dear-imgui-winit = "0.8.0"
dear-imgui-glow = "0.8.0"

tracing = { version = "0.1.44", features = ["log"] }
tracing-subscriber = "0.3.22"
log = "0.4.29"
